USE `asesco_prueba_1`

CREATE TABLE `gestion` (
  `gestion_id` int NOT NULL AUTO_INCREMENT,
  `nombre_gestor` varchar(100) DEFAULT NULL,
  `efectos_gestion` varchar(20) DEFAULT NULL,
  `tipo_de_contacto` varchar(100) DEFAULT NULL,
  `acuerdo_pago` decimal(25,2) DEFAULT NULL,
  `tipo_negocioacion` varchar(100) DEFAULT NULL,
  `canal_de_atencion` varchar(100) DEFAULT NULL,
  `motivo_no_pago` varchar(100) DEFAULT NULL,
  `gestion` text,
  `fecha_proxima_accion` date DEFAULT NULL,
  `fecha_ultima_gestion` date DEFAULT NULL,
  `telefono_contacto1` varchar(10) DEFAULT NULL,
  `telefono_contacto2` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`gestion_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `cartera_general` (
  `cartera_id` int NOT NULL AUTO_INCREMENT,
  `cedula_deudor` varchar(20) DEFAULT NULL,
  `nombre_deudor` varchar(100) DEFAULT NULL,
  `segmento` varchar(20) DEFAULT NULL,
  `prioridad` varchar(20) DEFAULT NULL,
  `dias_bq` int DEFAULT NULL,
  `saldo_bq` decimal(25,2) DEFAULT NULL,
  `tramos_bq` varchar(20) DEFAULT NULL,
  `dias_cd` int DEFAULT NULL,
  `tramo_cd` varchar(20) DEFAULT NULL,
  `saldo_cd` decimal(25,2) DEFAULT NULL,
  `rodamiento` varchar(20) DEFAULT NULL,
  `abono_captial` decimal(25,2) DEFAULT NULL,
  `valor_couta` decimal(25,2) DEFAULT NULL,
  `saldo_vencido_bq` decimal(25,2) DEFAULT NULL,
  `total_coutas` int DEFAULT NULL,
  `coutas_pagadas` int DEFAULT NULL,
  `coutas_por_pagar` int DEFAULT NULL,
  `coutas_mora` int DEFAULT NULL,
  `coutas_por_vencer` int DEFAULT NULL,
  `calf_interna` varchar(10) DEFAULT NULL,
  `f_venta` date DEFAULT NULL,
  `f_vencim` date DEFAULT NULL,
  `f_castigo` date DEFAULT NULL,
  `anos_castigo` int DEFAULT NULL,
  `bandas` varchar(20) DEFAULT NULL,
  `fe_ultimo_pago` date DEFAULT NULL,
  `tarifa` decimal(5,2) DEFAULT NULL,
  `saldo_capital` decimal(25,2) DEFAULT NULL,
  `saldo_capital_2` decimal(25,2) DEFAULT NULL,
  `interes_corriente` decimal(25,2) DEFAULT NULL,
  `iva_interes_cte` decimal(25,2) DEFAULT NULL,
  `interes_mora` decimal(25,2) DEFAULT NULL,
  `vlr_fondo_garantias` decimal(25,2) DEFAULT NULL,
  `seguro_deudor` decimal(25,2) DEFAULT NULL,
  `seguro_voluntario` decimal(25,2) DEFAULT NULL,
  `ley_mipymes` decimal(25,2) DEFAULT NULL,
  `reestructuracion` decimal(25,2) DEFAULT NULL,
  `refinanciacion` decimal(25,2) DEFAULT NULL,
  `flexibilizacion` decimal(25,2) DEFAULT NULL,
  `alivio` decimal(25,2) DEFAULT NULL,
  `papeleria` decimal(25,2) DEFAULT NULL,
  `centrales_riesgo` decimal(25,2) DEFAULT NULL,
  `tecnologia` decimal(25,2) DEFAULT NULL,
  `estudio_credito` decimal(25,2) DEFAULT NULL,
  `honorarios_de_cobranza` decimal(25,2) DEFAULT NULL,
  `iva_honorarios` decimal(25,2) DEFAULT NULL,
  `total_liquidacion` decimal(25,2) DEFAULT NULL,
  `capital` decimal(25,2) DEFAULT NULL,
  `otros_cargos` decimal(25,2) DEFAULT NULL,
  `honorarios_minimos_cobranza` decimal(25,2) DEFAULT NULL,
  `iva_honorarios_2` decimal(25,2) DEFAULT NULL,
  `total_liquidacion_2` decimal(25,2) DEFAULT NULL,
  `descuento` text,
  `producto` text,
  `factura` varchar(100) DEFAULT NULL,
  `regional` varchar(100) DEFAULT NULL,
  `ciudad` varchar(100) DEFAULT NULL,
  `tipo_cartera` varchar(100) DEFAULT NULL,
  `etapa_de_cobro` varchar(100) DEFAULT NULL,
  `garantias` varchar(100) DEFAULT NULL,
  `recaudo_total` decimal(25,2) DEFAULT NULL,
  `recaudo_cliente` decimal(25,2) DEFAULT NULL,
  `recaudo_asesco` decimal(25,2) DEFAULT NULL,
  `recaudo_iva_asesco` decimal(25,2) DEFAULT NULL,
  `personalidad_deduro` varchar(100) DEFAULT NULL,
  `va_promesa` decimal(25,2) DEFAULT NULL,
  `estado_barrido` varchar(100) DEFAULT NULL,
  `telefono_1` varchar(10) DEFAULT NULL,
  `telefono_2` varchar(10) DEFAULT NULL,
  `telefono_3` varchar(10) DEFAULT NULL,
  `telefono_4` varchar(10) DEFAULT NULL,
  `direccion_titular` varchar(255) DEFAULT NULL,
  `correo_titular` varchar(100) DEFAULT NULL,
  `eps_titular` varchar(100) DEFAULT NULL,
  `regimen` varchar(100) DEFAULT NULL,
  `telefono_eps` varchar(10) DEFAULT NULL,
  `direccion_eps` varchar(255) DEFAULT NULL,
  `correo_eps` varchar(100) DEFAULT NULL,
  `nit_eps` varchar(20) DEFAULT NULL,
  `empresa_eps` varchar(100) DEFAULT NULL,
  `matricula_snr` varchar(100) DEFAULT NULL,
  `ciudad_snr` varchar(100) DEFAULT NULL,
  `direccion_snr` varchar(255) DEFAULT NULL,
  `cedula_cod` varchar(20) DEFAULT NULL,
  `nombre_cod` varchar(100) DEFAULT NULL,
  `direccion_cod` varchar(255) DEFAULT NULL,
  `ciudad_cod` varchar(100) DEFAULT NULL,
  `correo_cod` varchar(100) DEFAULT NULL,
  `telefono_cod` varchar(10) DEFAULT NULL,
  `eps_cod` varchar(100) DEFAULT NULL,
  `regimen_cod` varchar(50) DEFAULT NULL,
  `cedula_cod_2` varchar(20) DEFAULT NULL,
  `nombre_cod_2` varchar(100) DEFAULT NULL,
  `direccion_cod_2` varchar(255) DEFAULT NULL,
  `ciudad_cod_2` varchar(100) DEFAULT NULL,
  `correo_cod_2` varchar(100) DEFAULT NULL,
  `telefono_cod_2` varchar(10) DEFAULT NULL,
  `eps_cod_2` varchar(100) DEFAULT NULL,
  `regimen_cod_2` varchar(50) DEFAULT NULL,
  `cedula_cod_3` varchar(20) DEFAULT NULL,
  `nombre_cod_3` varchar(100) DEFAULT NULL,
  `direccion_cod_3` varchar(255) DEFAULT NULL,
  `ciudad_cod_3` varchar(100) DEFAULT NULL,
  `correo_cod_3` varchar(100) DEFAULT NULL,
  `telefono_cod_3` varchar(10) DEFAULT NULL,
  `eps_cod_3` varchar(100) DEFAULT NULL,
  `regimen_cod_3` varchar(50) DEFAULT NULL,
  `observacion` text,
  `total_cliente` decimal(25,2) DEFAULT NULL,
  `empresa_encargada` varchar(100) DEFAULT NULL,
  `f_asignacion` date DEFAULT NULL,
  `f_expedicion` date DEFAULT NULL,
  `nit_int` varchar(20) DEFAULT NULL,
  `nombre_int_fin` varchar(100) DEFAULT NULL,
  `fondo_garantias` varchar(100) DEFAULT NULL,
  `fecha_ult_abono_fg` date DEFAULT NULL,
  `valor_abono_total` decimal(25,2) DEFAULT NULL,
  `ano_pago_fg` int DEFAULT NULL,
  `altura_recl_fg` int DEFAULT NULL,
  `cobertura_fg` int DEFAULT NULL,
  `estado_proceso` varchar(100) DEFAULT NULL,
  `n_radicado` varchar(100) DEFAULT NULL,
  `juzgado_conocimiento` text,
  `demandado_1` varchar(100) DEFAULT NULL,
  `demandado_2` varchar(100) DEFAULT NULL,
  `etapa_procesal` varchar(100) DEFAULT NULL,
  `fecha_de_etapa` date DEFAULT NULL,
  `actividad` varchar(100) DEFAULT NULL,
  `fecha_actividad` date DEFAULT NULL,
  `concepto_viabilidad_juridica` varchar(100) DEFAULT NULL,
  `garantias_juridica` varchar(100) DEFAULT NULL,
  `gestion_id` int DEFAULT NULL,
  `ref_1` varchar(100) DEFAULT NULL,
  `tel_ref_1` varchar(10) DEFAULT NULL,
  `ref_2` varchar(100) DEFAULT NULL,
  `tel_ref_2` varchar(10) DEFAULT NULL,
  `ref_3` varchar(100) DEFAULT NULL,
  `tel_ref_3` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`cartera_id`),
  KEY `fk_gestion` (`gestion_id`),
  CONSTRAINT `fk_gestion` FOREIGN KEY (`gestion_id`) REFERENCES `gestion` (`gestion_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
